/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cursoemvideo.olamundo;

import java.util.ArrayList;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author fagner.soares
 */
public class OlaMundoJava extends javax.swing.JFrame {

    /**
     * Creates new form OlaMundoJava
     */
    
    ArrayList alunos;
    
    public OlaMundoJava() {
        alunos = new ArrayList();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        alunolbl = new javax.swing.JLabel();
        alunoinput = new javax.swing.JTextField();
        nota1lbl = new javax.swing.JLabel();
        nota2lbl = new javax.swing.JLabel();
        nota1input = new javax.swing.JTextField();
        nota2input = new javax.swing.JTextField();
        calcularbtn = new javax.swing.JToggleButton();
        mostrrbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listapane = new javax.swing.JTextPane();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        alunolbl.setText("Aluno");

        alunoinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoinputActionPerformed(evt);
            }
        });

        nota1lbl.setText("Nota 1");

        nota2lbl.setText("Nota 2");

        nota1input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nota1inputActionPerformed(evt);
            }
        });

        nota2input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nota2inputFocusLost(evt);
            }
        });

        calcularbtn.setText("Adicionar Bença");
        calcularbtn.setEnabled(false);
        calcularbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularbtnActionPerformed(evt);
            }
        });

        mostrrbtn.setText("Mostra alunos");
        mostrrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrrbtnActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listapane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(calcularbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(mostrrbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nota2lbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(nota2input))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nota1lbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(nota1input))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(alunolbl)
                                    .addGap(18, 18, 18)
                                    .addComponent(alunoinput, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alunolbl)
                    .addComponent(alunoinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nota1lbl)
                    .addComponent(nota1input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nota2lbl)
                    .addComponent(nota2input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(calcularbtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(mostrrbtn)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alunoinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alunoinputActionPerformed

    private void nota1inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nota1inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nota1inputActionPerformed

    private void calcularbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularbtnActionPerformed
        // TODO add your handling code here:
        String nome = alunoinput.getText();
        double nota1 = Double.parseDouble(nota1input.getText());
        double nota2 = Double.parseDouble(nota2input.getText());
        Aluno a = new Aluno(nome, nota1, nota2);
        a.calcularMedia(nota1, nota2);
        
        alunoinput.setText("");
        nota1input.setText("");
        nota2input.setText("");
        
        //mostra na tela se for label.
//        resultadolbl.setText(a.toString());

        alunos.add(a);
        
    }//GEN-LAST:event_calcularbtnActionPerformed

    private void nota2inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nota2inputFocusLost
        // TODO add your handling code here:
        double nota1 = Double.parseDouble(nota1input.getText());
        double nota2 = Double.parseDouble(nota2input.getText());
        if (nota1 < 0 || nota2 < 0) {
            showMessageDialog(null, "A nota não pode ser negativa");
        } else if (nota1 > 10 || nota2 > 10) {
            showMessageDialog(null, "A nota não pode ser maior que 10");
        }else{
            calcularbtn.setEnabled(true);
        }
    }//GEN-LAST:event_nota2inputFocusLost

    private void mostrrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrrbtnActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i<=alunos.size(); i++){
            listapane.setText(listapane.getText() + alunos.get(i) + "\n");
        }
    }//GEN-LAST:event_mostrrbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OlaMundoJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OlaMundoJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OlaMundoJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OlaMundoJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OlaMundoJava().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alunoinput;
    private javax.swing.JLabel alunolbl;
    private javax.swing.JToggleButton calcularbtn;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane listapane;
    private javax.swing.JButton mostrrbtn;
    private javax.swing.JTextField nota1input;
    private javax.swing.JLabel nota1lbl;
    private javax.swing.JTextField nota2input;
    private javax.swing.JLabel nota2lbl;
    // End of variables declaration//GEN-END:variables
}
